name: Build - NO Trigger for now

#on:
  #push:
   # paths:
   #   - 'frontend/**'
#  pull_request:
 #  paths:
     # - 'frontend/**'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build Docker Image for Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t hr-backend ./frontend/
